### ISSUE TITLE
json加注释报错

### ISSUE THREAD

**Issue by zhouxinkai** [flutterchina/json_model#17]
![image](https://user-images.githubusercontent.com/13215870/67562206-dbe25b80-f750-11e9-92dd-a7edd6e7604d.png)

**Comment by zhouxinkai** [comment]
Unhandled exception:
FormatException: Unexpected character (at line 3, character 22)
  "father": "$user", //Other class model
                     ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:922:48)
#2      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
#3      JsonDecoder.convert (dart:convert/json.dart:493:36)
#4      JsonCodec.decode (dart:convert/json.dart:151:41)
#5      walk.<anonymous closure> (file:///Users/brucezhou/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/json_model-0.0.2/bin/json_model.dart:46:22)
#6      List.forEach (dart:core-patch/growable_array.dart:283:8)
#7      walk (file:///Users/brucezhou/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/json_model-0.0.2/bin/json_model.dart:38:8)
#8      main (file:///Users/brucezhou/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/json_model-0.0.2/bin/json_model.dart:18:6)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by zhouxinkai** [comment]
修改源码已解决

**Comment by zhouxinkai** [comment]
![image](https://user-images.githubusercontent.com/13215870/67563849-2913fc80-f754-11e9-83ae-42fcddf03e76.png)

**Comment by mcdull729** [comment]
json文件还是不能有注释

**Comment by szaquila** [comment]
var map = json.decode(file.readAsStringSync().replaceAll(RegExp(r"[, ]//.*\n"), "\n"));  // 正则替换掉注释

**Comment by dbsxdbsx** [comment]
> json文件还是不能有注释

确实，即使目前，json里还是不能有注释
